
<RootWidget>:

    Button:
        size_hint: None, None #Uso exclusivo dos gerenciadores
        size: 350, 50
        x: 100
        y: 350
        text: "px"

    Button:
        size_hint: None, None #Uso exclusivo dos gerenciadores
        size: dp(350), dp(50)
        pos: dp(100), dp(270)
        text: "dp"


    Button:
        size_hint: .5, .09 #Uso exclusivo dos gerenciadores
        pos_hint: {"x": .1, "y": .1}  #Uso exclusivo dos gerenciadores
        text: "%"
