

# isso é um comentario

#A Linha abaixo é uma importação de pacotes python
#:import o os

#A linha abaixo é uma definição de uma variavél
#:set x 10


<MeuBotao@Button>:
    text: "botao"

<Tela@BoxLayout>:
    orientation: "horizontal"

#    Button:
#        text: "bt1"
#
#    Button:
#        text: "bt2"
#
#    Button:
#        text: "bt3"

    MeuBotao:
    MeuBotao:
        text: "ufuj"
    MeuBotao:

Tela: