

# isso é um comentario

#A Linha abaixo é uma importação de pacotes python
#:import o os

#A linha abaixo é uma definição de uma variavél
#:set x 10





<MinhaTela@BoxLayout>:
    orientation: "vertical"

    Button:
        text: "self"
        on_press: self.click()

    Button:
        text: "root"
        on_press: root.click()

    Button:
        text: "app"
        on_press: app.click()

MinhaTela: